Your CarPi is booted into maintenance mode.
In this mode you can configure system settings, update the software and run other maintenance tasks to keep your CarPi in shape.
You need a keyboard for this task.

If you are unable to use maintenance mode, unplug the power cord and reconnect it after a few seconds. CarPi will then start normally again.

Connect a keyboard via USB and press OK (ENTER) to proceed.
